# SPDX-FileCopyrightText: 2023-2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025, 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Moodist paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ moodist_uid }}"
    group: "{{ moodist_gid }}"
  with_items:
    - "{{ moodist_base_path }}"
    - "{{ moodist_src_path }}"

- name: Ensure Moodist support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ moodist_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ moodist_uid }}"
    group: "{{ moodist_gid }}"
  with_items:
    - env
    - labels
  register: moodist_support_files_result

- name: Run if self-building of Moodist container image is not enabled
  when: "not moodist_container_image_self_build | bool"
  block:
    - name: Ensure Moodist container image is pulled via community.docker.docker_image
      when: sysd_docker_image_pull_method == 'ansible-module'
      community.docker.docker_image:
        name: "{{ moodist_container_image }}"
        source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
        force_source: "{{ moodist_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else moodist_container_image_force_pull }}"
      register: moodist_container_image_pull_result
      retries: "{{ container_retry }}"
      delay: "{{ container_retry_delay }}"
      until: moodist_container_image_pull_result is not failed

    - name: Ensure Moodist container image is pulled via ansible.builtin.command
      when: sysd_docker_image_pull_method == 'command'
      ansible.builtin.command:
        cmd: "{{ sysd_docker_host_command }} pull {{ moodist_container_image }}"
      register: moodist_container_image_pull_result
      retries: "{{ container_retry }}"
      delay: "{{ container_retry_delay }}"
      until: moodist_container_image_pull_result is not failed
      changed_when: "'Downloaded newer image' in moodist_container_image_pull_result.stdout"

- name: Run if self-building of Moodist container image is enabled
  when: "moodist_container_image_self_build | bool"
  block:
    - name: Ensure Moodist custom source files are installed
      ansible.builtin.template:
        src: "{{ role_path }}/templates/src/{{ item }}.j2"
        dest: "{{ moodist_src_path }}/{{ item }}"
        mode: "0640"
        owner: "{{ moodist_uid }}"
        group: "{{ moodist_gid }}"
      with_items:
        - donate.tsx
      register: moodist_installation_custom_results

    - name: Ensure Moodist repository is present on self-build
      ansible.builtin.git:
        repo: "{{ moodist_container_image_self_build_repo }}"
        version: "{{ moodist_container_image_self_build_repo_version }}"
        dest: "{{ moodist_container_image_self_build_src_files_path }}"
        force: "yes"
      register: moodist_git_pull_results

    - name: Ensure Moodist source files are replaced with the custom files
      when: "moodist_container_image_self_build_custom | bool"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
        owner: root
        group: root
        force: true
        remote_src: true
      with_items:
        - { src: "{{ moodist_src_path }}/donate.tsx", dest: "{{ moodist_container_image_self_build_src_files_path }}/src/components/categories/donate/donate.tsx" }

    - name: Ensure Moodist files for building container image installed
      ansible.builtin.template:
        src: "{{ role_path }}/templates/{{ item }}.j2"
        dest: "{{ moodist_container_image_self_build_src_files_path }}/{{ item }}"
        mode: "0640"
        owner: "{{ moodist_uid }}"
        group: "{{ moodist_gid }}"
        force: true # Overwrite the default Dockerfile at https://raw.githubusercontent.com/remvze/moodist/refs/heads/main/Dockerfile
      with_items:
        - .dockerignore
        - Dockerfile

    - name: Check if Moodist container image exists to avoid recreating the same one
      ansible.builtin.command: docker images -q "{{ moodist_container_image_self_build_name }}"
      register: moodist_docker_image_exists
      changed_when: false

    - name: Ensure Moodist container image is built if the container image does not exist or the repository has been updated
      community.docker.docker_image:
        name: "{{ moodist_container_image_self_build_name }}"
        source: build
        force_source: "{{ moodist_docker_image_exists.stdout == '' or moodist_installation_custom_results.changed or (moodist_git_pull_results.before != moodist_git_pull_results.after) if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
        force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else moodist_docker_image_exists.stdout == '' or moodist_installation_custom_results.changed or (moodist_git_pull_results.before != moodist_git_pull_results.after) }}"
        build:
          dockerfile: Dockerfile
          path: "{{ moodist_container_image_self_build_src_files_path }}"
          pull: true
          args:
      register: moodist_container_image_build_result

- name: Ensure Moodist container network is created via community.docker.docker_network
  when: sysd_docker_net_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ sysd_docker_ipv6_enabled }}"
    name: "{{ moodist_container_network }}"
    driver: bridge
    driver_options: "{{ sysd_docker_net_driver_opts }}"
  register: moodist_network_creation_result

- name: Ensure Moodist container network is created via ansible.builtin.command
  when: sysd_docker_net_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ sysd_docker_host_command }} network create
      {% if sysd_docker_ipv6_enabled %}--ipv6{% endif %}
      {{ sysd_docker_net_driver_opts_string }}
      {{ moodist_container_network }}
  register: moodist_network_creation_result
  changed_when: moodist_network_creation_result.rc == 0
  failed_when: moodist_network_creation_result.rc != 0 and 'already exists' not in moodist_network_creation_result.stderr

- name: Ensure Moodist systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/moodist.service.j2"
    dest: "{{ sysd_docker_service_path }}/{{ moodist_identifier }}.service"
    mode: "0644"
  register: moodist_systemd_service_result

- name: Determine whether Moodist needs a restart
  ansible.builtin.set_fact:
    moodist_restart_necessary: >-
      {{
        moodist_support_files_result.changed | default(false)
        or moodist_systemd_service_result.changed | default(false)
        or moodist_container_image_pull_result.changed | default(false)
        or moodist_container_image_build_result.changed | default(false)
      }}
