# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Moodist installation tasks
  when: moodist_enabled | bool
  tags:
    - setup-all
    - setup-moodist
    - install-all
    - install-moodist
  block:
    - name: Validate Moodist configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Moodist
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Moodist uninstallation tasks
  when: not moodist_enabled | bool
  tags:
    - setup-all
    - setup-moodist
  block:
    - name: Uninstall Moodist
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
