# SPDX-FileCopyrightText: 2023, 2024 Slavi Pantaleev
# SPDX-FileCopyrightText: 2024 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of Moodist systemd service
  ansible.builtin.stat:
    path: "{{ sysd_docker_service_path }}/{{ moodist_identifier }}.service"
  register: moodist_service_stat

- name: Uninstall Moodist systemd services and files
  when: moodist_service_stat.stat.exists | bool
  block:
    - name: Ensure Moodist systemd service is stopped
      ansible.builtin.service:
        name: "{{ moodist_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Moodist systemd service does not exist
      ansible.builtin.file:
        path: "{{ sysd_docker_service_path }}/{{ moodist_identifier }}.service"
        state: absent

    - name: Ensure Moodist container network does not exist
      when: moodist_container_network_deletion_enabled
      block:
        - name: Ensure Moodist container network does not exist via community.docker.docker_network
          when: sysd_docker_net_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ moodist_container_network }}"
            state: absent
          register: moodist_network_deletion_result

        - name: Ensure Moodist container network does not exist via ansible.builtin.command
          when: sysd_docker_net_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ sysd_docker_host_command }} network rm
              {{ moodist_container_network }}
          register: moodist_network_deletion_result
          changed_when: moodist_container_network in moodist_network_deletion_result.stdout

    - name: Ensure Moodist path does not exist
      ansible.builtin.file:
        path: "{{ moodist_base_path }}"
        state: absent
