{#
SPDX-FileCopyrightText: 2025 Suguru Hirahara

SPDX-License-Identifier: AGPL-3.0-or-later
#}

FROM node:lts AS build

WORKDIR /app

# Copy the application source code
COPY package*.json ./

RUN npm install

COPY . .

# Build the application
RUN npm run build

# Use a lighter base image for the production environment
FROM node:lts-trixie-slim

COPY --from=build /app/dist /public

# Install http-server for serving the page as non-root user
RUN npm install -g http-server

EXPOSE "{{ moodist_container_http_port }}"

CMD ["http-server", "", "--port", "{{ radicle_explorer_container_http_port }}", "--gzip"]
