{#
SPDX-FileCopyrightText: 2025 Suguru Hirahara

SPDX-License-Identifier: AGPL-3.0-or-later
#}

FROM node:lts AS build

WORKDIR /app

# Copy the application source code
COPY package*.json ./

RUN npm install

COPY . .

# Build the application
RUN npm run build

# Use a lighter base image for the production environment
FROM joseluisq/static-web-server:latest

COPY --from=build /app/dist {{ moodist_environment_variables_server_root }}

EXPOSE "{{ moodist_container_http_port }}"
